### PR TITLE
Change mimemail:parameters() to be a map with atom keys

### PR DESCRIPTION
**Pull request by seriyps**
As discussed in #188.

I can also add compatibility function that will internally convert proplist with binary keys to map with atom keys and emit some warning?

Should probably replace space indentation with tab one. For some reason .editorconfig haven't made it for me.

### CODE REVIEW

**Comment by mworrell** [comment]
I like this change - it is much more erlangy and makes type checking easier.

I add it to the 1.0 milestone.

**Comment by seriyps** [comment]
I guess this one can now be merged?

**Comment by mworrell** [comment]
Yes, we can start merging our breaking changes!

**Comment by seriyps** [comment]
Thanks!

**Pull request merged**
