### PR TITLE
Iconv fixes

### PR DESCRIPTION
**Pull request by arjan**
See #132

### CODE REVIEW

**Comment by seriyps** [comment]
Looks good

**Comment by arjan** [comment]
Yes.. well, I have to see why the tests are suddenly failing, seeminly randomly, need to bisect this, the PR was quite old.

**Comment by seriyps** [comment]
Well, there are some race-conditions in tests. Some of them I tried to fix in #170 but probably not all of them.
I can try to take a look.

**Comment by arjan** [comment]
Thanks @MonsieurV for your contribution, it only took us almost 2 years to merge this ;-)

**Comment by MonsieurV** [comment]
Ahah, glad to see it merged! :sweat_smile: Thanks @arjan & others

I've tested it on my app. Works great!

Is there a release date scheduled for these changes on [Hex](https://hex.pm/packages/gen_smtp)?

**Pull request merged**
