### PR TITLE
Add `sockopts` options `ciphers`

### LINKED ISSUE #176: Add sockopts option `ciphers` to enable insecure protocols
I use `gen_smtp` (from Elixir) to send mail relay `smtp.exmail.qq.com` with ssl: true
it will throw `handshake_failure` by default

```elixir
{:error, :retries_exceeded,
 {:network_failure, '113.96.200.115',
  {:error,
   {:tls_alert,
    {:handshake_failure,
     'TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure\n'}}}}}
``` 

this would be resolved by add sockopts `ciphers` which skipped by [SSL_CONNECT_OPTIONS](https://github.com/Vagabond/gen_smtp/blob/master/src/smtp_socket.erl#L46) currently.
Is there some way to pass `ciphers` opts to inner `ssl:connect`  or resolv this issue. 

### Reference Code
```elixir
ciphers = :ssl.cipher_suites(:all)
sockopts = [
  ciphers: ciphers
]
opts = [
  relay: 'smtp.exmail.qq.com',
  username: 'dayu@helijia.com',
  password: xxx,
  ssl: true,
  sockopts: sockopts,
]
res = :gen_smtp_client.send_blocking({
  'dayu@helijia.com', ['bencode@163.com'],
  'Subject: hello dayu\r\nFrom: <dayu@helijia.com> \r\nTo: <bencode@163.com> \r\n\r\nThis is the email body'
}, opts)
```

### PR DESCRIPTION
**Pull request by xosdy**
This closes #176.

### CODE REVIEW

**Comment by seriyps** [comment]
This `ssl:cipher_suites()` is quite a big list... 52 items  Is there any way to avoid "materializing" it by default?

```
> erts_debug:flat_size(ssl:cipher_suites()) * erlang:system_info(wordsize).
2696
```

**Comment by xosdy** [comment]
I add a list to filter SSL options keys, so leave default ciphers handled by the `ssl` module.

**Comment by xinz** [comment]
@seriyps do we have any progress on this?

**Comment by seriyps** [comment]
it looks good for me. I don't have merge permissions, so it's up to @mworrell / @Vagabond / @arjan

**Comment by mworrell** [comment]
Merging, thanks!

**Pull request merged**
