### PR TITLE
Drop support for Ranch below 1.6.0

### PR DESCRIPTION
**Pull request by seriyps**
Again, those who need older Ranch (eg, they use Cowboy 1.x) can use gen_smtp 1.0

### CODE REVIEW

**Comment by arjan** [comment]
Looks good. Next is dropping Erlang < 19? :-)

**Comment by mworrell** [comment]
We are now at Erlang 23, so I am good with dropping < 21.
Then we support the last three releases.

**Comment by seriyps** [comment]
I already created a PR to drop OTP-18. But OTP-19 is 0-effort to support right now, so, dropping it will be just removing 1 line from .travis.yml.
Dropping OTP <21 will help a bit (we have some `-ifdef`'s for pre-21 versions; also we are only able to build edocs on OTP-21+), but effort to support OTP-19+ is not that high so far.

**Comment by aptinio** [comment]
I tried adding [master](/gen-smtp/gen_smtp/tree/master) as a dependency in an Elixir project and I got:

```
(Hex.Version.InvalidRequirementError) invalid requirement: "^1.6.2 || ^2"
```

I'm not familiar with rebar but I wonder if using `~>` instead of `^` would help.

**Comment by arjan** [comment]
Thanks @aptinio, trying to fix this in #227.

**Pull request merged**
