### PR TITLE
Implement GitHub Actions

### LINKED ISSUE #230: Move from Travis CI to GitHub Actions?
Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions, or at least adds GitHub Actions alongside Travis CI? It seems travis-ci.org will stop being useful from Dec 31 2020. I can do it, except that I think you need to create the workflow yml, first, in `master`, after which I can branch off of.

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
~~You might also want to reference the "build" status in `README.md`.~~

I think you need to "activate" GitHub Actions on `master` after which I can rebase this for testing.

Closes #230.

**Note**: I'm unsure about the proper syntax for `[[ ${{matrix.os}} < 21 ]] || make docs` inside the GHA yml, but I'll see it produce some result as soon as GHA workflow runs.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
> You might also want to reference the "build" status in README.md.

Don't merge just yet. Let me handle this.

**Comment by paulo-ferraz-oliveira** [comment]
Hi. Is this OK for merging? Do you want further changes?

**Comment by paulo-ferraz-oliveira** [comment]
Ping.

**Comment by mworrell** [comment]
Looks great to me.  Thank you!

**Pull request merged**
